name: image_auto_slider
description: image slide.
version: 0.0.1
author: Kohei Niimi <kohei.niiimi@gupuru.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter