name: image_auto_slider
description: image slide.
version: 0.0.2
homepage: https://github.com/gupuru/ImageAutoSlider

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter